type Query {
  post(id: ID!): Post!
  posts(limit: Int!, offset: Int!): [Post!]!
  login(email: String!, password: String!): LoginResponse
}

type Mutation {
  createPost(author: ID!, title: String!, content: String, createdAt: String!): String!
  createComment(postId: ID!, author: ID!, content: String!, createdAt: String!): String!
  registerUser(username: String!, email: String!, password: String!, createdAt: String!): String!
}
